/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Demo: typeof import('./src/components/Demo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    IEpCircleCheckFilled: typeof import('~icons/ep/circle-check-filled')['default']
    IEpEditPen: typeof import('~icons/ep/edit-pen')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
